sudo: required

language: generic

services:
  - Docker
  
before_install:
  - docker build -t developbuild -f Dockerfile.dev .
  
script:
  - docker run -e CI=true developbuild npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-2-074134644622"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
